import { remove as removeDiacritics } from 'diacritics'

function normalizeCompare(a: string, b: string) {
    return normalize(a).localeCompare(normalize(b))
}

function normalize(val: string) {
    return removeDiacritics('' + (val || ''))
        .toLowerCase()
        .trim()
}

export const themes = [
    'a11y-dark',
    'a11y-light',
    'agate',
    'an-old-hope',
    'androidstudio',
    'arduino-light',
    'arta',
    'ascetic',
    'atom-one-dark-reasonable',
    'atom-one-dark',
    'atom-one-light',
    'brown-paper',
    'codepen-embed',
    'color-brewer',
    'dark',
    'default',
    'devibeans',
    'docco',
    'far',
    'felipec',
    'foundation',
    'github-dark-dimmed',
    'github-dark',
    'github',
    'gml',
    'googlecode',
    'gradient-dark',
    'gradient-light',
    'grayscale',
    'hybrid',
    'idea',
    'intellij-light',
    'ir-black',
    'isbl-editor-dark',
    'isbl-editor-light',
    'kimbie-dark',
    'kimbie-light',
    'lightfair',
    'lioshi',
    'magula',
    'mono-blue',
    'monokai-sublime',
    'monokai',
    'night-owl',
    'nnfx-dark',
    'nnfx-light',
    'nord',
    'obsidian',
    'panda-syntax-dark',
    'panda-syntax-light',
    'paraiso-dark',
    'paraiso-light',
    'pojoaque',
    'purebasic',
    'qtcreator-dark',
    'qtcreator-light',
    'rainbow',
    'routeros',
    'school-book',
    'shades-of-purple',
    'srcery',
    'stackoverflow-dark',
    'stackoverflow-light',
    'sunburst',
    'tokyo-night-dark',
    'tokyo-night-light',
    'tomorrow-night-blue',
    'tomorrow-night-bright',
    'vs',
    'vs2015',
    'xcode',
    'xt256'
].sort(normalizeCompare)

export const languages = Object.entries({
    '1C': '1c',
    'ABNF': 'abnf',
    'Access logs': 'accesslog',
    'Ada': 'ada',
    'Arduino (C++ w/Arduino libs)': 'arduino',
    'ARM assembler': 'armasm',
    'AVR assembler': 'avrasm',
    'ActionScript': 'actionscript',
    'AngelScript': 'angelscript',
    'Apache': 'apache',
    'AppleScript': 'applescript',
    'Arcade': 'arcade',
    'AsciiDoc': 'asciidoc',
    'AspectJ': 'aspectj',
    'AutoHotkey': 'autohotkey',
    'AutoIt': 'autoit',
    'Awk': 'awk',
    'Bash': 'bash',
    'Basic': 'basic',
    'BNF': 'bnf',
    'Brainfuck': 'brainfuck',
    'C#': 'csharp',
    'C': 'c',
    'C++': 'cpp',
    'C/AL': 'cal',
    'Cache Object Script': 'cos',
    'CMake': 'cmake',
    'Coq': 'coq',
    'CSP': 'csp',
    'CSS': 'css',
    'Cap’n Proto': 'capnproto',
    'Clojure': 'clojure',
    'CoffeeScript': 'coffeescript',
    'Crmsh': 'crmsh',
    'Crystal': 'crystal',
    'D': 'd',
    'Dart': 'dart',
    'Delphi': 'dpr',
    'Diff': 'diff',
    'Django': 'django',
    'DNS Zone file': 'dns',
    'Dockerfile': 'dockerfile',
    'DOS': 'dos',
    'dsconfig': 'dsconfig',
    'DTS (Device Tree)': 'dts',
    'Dust': 'dust',
    'EBNF': 'ebnf',
    'Elixir': 'elixir',
    'Elm': 'elm',
    'Erlang': 'erlang',
    'Excel': 'excel',
    'F#': 'fsharp',
    'FIX': 'fix',
    'Fortran': 'fortran',
    'G-Code': 'gcode',
    'Gams': 'gams',
    'GAUSS': 'gauss',
    'Gherkin': 'gherkin',
    'Go': 'go',
    'Golo': 'golo',
    'Gradle': 'gradle',
    'GraphQL': 'graphql',
    'Groovy': 'groovy',
    'HTML, XML': 'xml',
    'HTTP': 'http',
    'Haml': 'haml',
    'Handlebars': 'handlebars',
    'Haskell': 'haskell',
    'Haxe': 'haxe',
    'Hy': 'hy',
    'Ini, TOML': 'ini',
    'Inform7': 'inform7',
    'IRPF90': 'irpf90',
    'JSON': 'json',
    'Java': 'java',
    'JavaScript': 'javascript',
    'Julia': 'julia',
    'Julia REPL': 'julia-repl',
    'Kotlin': 'kotlin',
    'LaTeX': 'tex',
    'Leaf': 'leaf',
    'Lasso': 'lasso',
    'Less': 'less',
    'LDIF': 'ldif',
    'Lisp': 'lisp',
    'LiveCode Server': 'livecodeserver',
    'LiveScript': 'livescript',
    'Lua': 'lua',
    'Makefile': 'makefile',
    'Markdown': 'markdown',
    'Mathematica': 'mathematica',
    'Matlab': 'matlab',
    'Maxima': 'maxima',
    'Maya Embedded Language': 'mel',
    'Mercury': 'mercury',
    'MIPS Assembler': 'mips',
    'Mizar': 'mizar',
    'Mojolicious': 'mojolicious',
    'Monkey': 'monkey',
    'Moonscript': 'moonscript',
    'N1QL': 'n1ql',
    'NSIS': 'nsis',
    'Nginx': 'nginx',
    'Nim': 'nim',
    'Nix': 'nix',
    'OCaml': 'ocaml',
    'Objective C': 'objectivec',
    'OpenGL Shading Language': 'glsl',
    'OpenSCAD': 'openscad',
    'Oracle Rules Language': 'ruleslanguage',
    'Oxygene': 'oxygene',
    'PF': 'pf',
    'PHP': 'php',
    'Parser3': 'parser3',
    'Perl': 'perl',
    'Plaintext': 'plaintext',
    'Pony': 'pony',
    'PostgreSQL & PL/pgSQL': 'pgsql',
    'PowerShell': 'powershell',
    'Processing': 'processing',
    'Prolog': 'prolog',
    'Properties': 'properties',
    'Protocol Buffers': 'proto',
    'Puppet': 'puppet',
    'Python': 'python',
    'Python profiler results': 'profile',
    'Python REPL': 'python-repl',
    'Q': 'k',
    'QML': 'qml',
    'R': 'r',
    'ReasonML': 'reasonml',
    'RenderMan RIB': 'rib',
    'RenderMan RSL': 'rsl',
    'Roboconf': 'graph',
    'Ruby': 'ruby',
    'Rust': 'rust',
    'SAS': 'SAS',
    'SCSS': 'scss',
    'SQL': 'sql',
    'STEP Part 21': 'p21',
    'Scala': 'scala',
    'Scheme': 'scheme',
    'Scilab': 'scilab',
    'Shell': 'shell',
    'Smali': 'smali',
    'Smalltalk': 'smalltalk',
    'SML': 'sml',
    'Stan': 'stan',
    'Stata': 'stata',
    'Stylus': 'stylus',
    'SubUnit': 'subunit',
    'Swift': 'swift',
    'Tcl': 'tcl',
    'Test Anything Protocol': 'tap',
    'Thrift': 'thrift',
    'TP': 'tp',
    'Twig': 'twig',
    'TypeScript': 'typescript',
    'VB.Net': 'vbnet',
    'VBScript': 'vbscript',
    'VHDL': 'vhdl',
    'Vala': 'vala',
    'Verilog': 'verilog',
    'Vim Script': 'vim',
    'X++': 'axapta',
    'x86 Assembly': 'x86asm',
    'XL': 'xl',
    'XQuery': 'xquery',
    'YAML': 'yml',
    'Zephir': 'zephir'
}).sort((a, b) => normalizeCompare(a[0], b[0]))
